// Initial mock data store with fallback persistence in localStorage

export const INITIAL_ROOMS = [
  {
    id: 1,
    name: "Conference Room A",
    capacity: 12,
    location: "2nd Floor, West Wing",
    description: "Spacious conference room equipped for executive board meetings and hybrid presentations.",
    amenities: ["WiFi", "Projector", "Display", "Video Conference", "Whiteboard"],
    is_active: true,
    status: "Available",
    type: "Conference Room",
    size: "large",
  },
  {
    id: 2,
    name: "Huddle Room 1",
    capacity: 6,
    location: "1st Floor, Tech Hub",
    description: "Compact private room designed for fast team syncs and stand-ups.",
    amenities: ["WiFi", "Display", "Whiteboard"],
    is_active: true,
    status: "Occupied",
    type: "Huddle Room",
    size: "small",
  },
  {
    id: 3,
    name: "The Boardroom",
    capacity: 20,
    location: "3rd Floor, Executive Suite",
    description: "Flagship boardroom with high-end audio-visual equipment and panoramic city views.",
    amenities: ["WiFi", "Projector", "Display", "Sound System", "Video Conference"],
    is_active: true,
    status: "Available",
    type: "Boardroom",
    size: "large",
  },
  {
    id: 4,
    name: "Meeting Room B",
    capacity: 8,
    location: "2nd Floor, East Wing",
    description: "Mid-sized collaborative room currently scheduled for AV maintenance.",
    amenities: ["WiFi", "Display"],
    is_active: false,
    status: "Maintenance",
    type: "Meeting Room",
    size: "medium",
  },
  {
    id: 5,
    name: "Training Room",
    capacity: 30,
    location: "1st Floor, Learning Center",
    description: "Large versatile training area with modular seating and dual presentation screens.",
    amenities: ["WiFi", "Projector", "Sound System", "Air Conditioning"],
    is_active: true,
    status: "Available",
    type: "Training Room",
    size: "large",
  },
  {
    id: 6,
    name: "Executive Room",
    capacity: 8,
    location: "3rd Floor, Executive Suite",
    description: "Confidential interview and executive negotiation meeting space.",
    amenities: ["WiFi", "Display", "Coffee Machine"],
    is_active: true,
    status: "Available",
    type: "Private Office",
    size: "medium",
  },
];

export const INITIAL_BOOKINGS = [
  {
    id: 1,
    room_id: 1,
    room_name: "Conference Room A",
    booker_name: "Jane Doe",
    title: "Quarterly Strategy Review",
    date: new Date().toISOString().split("T")[0],
    start_time: "09:00",
    end_time: "10:30",
    attendees: 10,
    status: "confirmed",
    color: "blue",
    notes: "Requires projector and video conference link",
  },
  {
    id: 2,
    room_id: 2,
    room_name: "Huddle Room 1",
    booker_name: "Mark Reyes",
    title: "Design Sprint Check-in",
    date: new Date().toISOString().split("T")[0],
    start_time: "13:00",
    end_time: "14:00",
    attendees: 4,
    status: "confirmed",
    color: "purple",
    notes: "Daily standup",
  },
  {
    id: 3,
    room_id: 3,
    room_name: "The Boardroom",
    booker_name: "Ana Cruz",
    title: "Executive Board Session",
    date: new Date().toISOString().split("T")[0],
    start_time: "15:00",
    end_time: "17:00",
    attendees: 16,
    status: "confirmed",
    color: "green",
    notes: "Catering requested",
  },
  {
    id: 4,
    room_id: 1,
    room_name: "Conference Room A",
    booker_name: "Carlos Mendoza",
    title: "Client Pitch & Demo",
    date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
    start_time: "10:00",
    end_time: "11:30",
    attendees: 8,
    status: "confirmed",
    color: "orange",
    notes: "External guests attending",
  },
  {
    id: 5,
    room_id: 5,
    room_name: "Training Room",
    booker_name: "Sarah Jenkins",
    title: "New Employee Onboarding",
    date: new Date(Date.now() + 86400000 * 2).toISOString().split("T")[0],
    start_time: "09:00",
    end_time: "12:00",
    attendees: 20,
    status: "confirmed",
    color: "pink",
    notes: "Training manuals prepared",
  },
];

export const INITIAL_USERS = [
  {
    id: 1,
    name: "System Administrator",
    email: "admin@company.com",
    role: "Administrator",
    created_at: "2026-01-15T08:00:00Z",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane.doe@company.com",
    role: "Manager",
    created_at: "2026-02-10T09:30:00Z",
  },
  {
    id: 3,
    name: "Mark Reyes",
    email: "mark.reyes@company.com",
    role: "Employee",
    created_at: "2026-03-01T11:15:00Z",
  },
  {
    id: 4,
    name: "Ana Cruz",
    email: "ana.cruz@company.com",
    role: "Manager",
    created_at: "2026-03-12T14:20:00Z",
  },
  {
    id: 5,
    name: "Carlos Mendoza",
    email: "carlos.m@company.com",
    role: "Employee",
    created_at: "2026-04-05T10:00:00Z",
  },
];

